cmake_minimum_required(VERSION 3.4)
project(solver_application)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(solver_lib STATIC ${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/solver.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/solver.h)
add_executable(solver_application ${CMAKE_CURRENT_SOURCE_DIR}/equation.cpp)
target_link_libraries(solver_application ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/build/libformatter_ex.a)
target_link_libraries(solver_application ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_lib/build/libformatter.a)
target_link_libraries(solver_application solver_lib)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/)
