cmake_minimum_required(VERSION 3.4)
project(solver_application)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(formatter STATIC ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_lib/formatter.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_lib/formatter.h)
add_library(formatter_ex STATIC ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/formatter_ex.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/formatter_ex.h)
target_link_libraries(formatter_ex formatter)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../formatter_lib/)
add_library(solver_lib STATIC ${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/solver.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/solver.h)
add_executable(solver_application ${CMAKE_CURRENT_SOURCE_DIR}/equation.cpp)
target_link_libraries(solver_application formatter_ex)
target_link_libraries(solver_application solver_lib)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../solver_lib/)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../formatter_ex_lib/)
